### ISSUE TITLE
Update "snappy" namespace 

### ISSUE THREAD

**Issue by onlyjob** [cznic/zappy#4]
"code.google.com/p/snappy-go/snappy" → "github.com/golang/snappy"

**Comment by onlyjob** [comment]
Thanks for quick action but the actual imports are not fixed:
https://github.com/cznic/zappy/blob/master/all_test.go#L26

**Comment by onlyjob** [comment]
All good, thank you.

**Comment by cznic** [comment]
You're welcome ;-)

**Comment by onlyjob** [comment]
:)
