### ISSUE TITLE
Zappy is broken and panics

### ISSUE THREAD

**Issue by leo-stone** [cznic/zappy#5]
Hi there,

both, the purego and cgo version are broken. I've attched an example byte slice which will cause
zappy to panic. 

this assumes this call is made: zappy.Encode(nil,the_data_to_encode)

here a little snippet to reproduce:
```
package main

import (
	"io/ioutil"

	"github.com/cznic/zappy"
)

func main() {

	the_bytes, _ := ioutil.ReadFile("zappy_error_src_dump_purego.bin")
	zappy.Encode(nil, the_bytes) //this will always panic  

}

```

[zappy_error_src_dump_purego.zip](https://github.com/cznic/zappy/files/378975/zappy_error_src_dump_purego.zip)

**Comment by cznic** [comment]
I'm sure I'm the worst C programmer in the local universes group.

A PR with a fix would be very welcome ;-)

**Comment by leo-stone** [comment]
@cznic  Hm, no time, but if it helps, I've got you a chunk that crashes both versions ...
I've updated the OP and it's attached file.

**Comment by cznic** [comment]
Data that crashes both versions are surely extremely helpful. Thanks!

**Comment by cznic** [comment]
Thanks for reporting this.
